#!/usr/bin/env python

import sys
import socket
import time


host = sys.argv[1]
port = int(sys.argv[2])

get_str = 'GET / HTTP/1.1\r\nHost: %s\r\n\r\n'
BUF_SIZE = 1024
server_addr = (host, port)
try : 
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
except socket.error, msg :
    print '[' + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + ']' + "Creating Socket Failure. Error Code : " + str(msg[0]) + " Message : " + msg[1]
    sys.exit()

try : 
    client.connect(server_addr)
except socket.error, msg :
    print '[' + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + ']' + "Connecting Socket Failure. Error Code : " + str(msg[0]) + " Message : " + msg[1]
    sys.exit()

print '[' + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + ']' + 'Connected to ' + host + ' on port ' + bytes(port)

try :
    client.sendall(get_str % host)
except socket.error, msg :
    print '[' + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + ']' + "Sending request Failure. Error Code : " + str(msg[0]) + " Message : " + msg[1]
    sys.exit()

start = time.time()
while True :
    data = client.recv(BUF_SIZE)
    if not data :
        break
    print data
    
end = time.time()
elapsed = end - start
print '[' + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + ']' + 'Connection Closed by ' + host + ':' + bytes(port) + ', elapse: ' + bytes(elapsed)
client.close()
